import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: 'Kuncie App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <meta name="color-scheme" content="light only"  />
      </head>
      <body>
        {children}
      </body>
    </html>
  );
}
